/**
 * TypeScript declarations for @cldmv/slothlet index
 * 
 * This file is auto-generated by tools/build-exports.mjs
 * Run: npm run build:exports to regenerate
 */

// Re-export all types from the main slothlet module
export type * from "./dist/slothlet.d.mts";
// If you want runtime exports, use the implementation file instead:
export * from "./dist/slothlet.mts";

// Auto-generated named export declarations (these override the re-export above)
export const _slothlet: any;
export const context: any;
export const mutateLiveBindingFunction: any;
export const reference: any;
export const self: any;

// Main slothlet export
declare const slothlet: any;
export default slothlet;
export { slothlet };
