/**
 * Type anchor for {@link self}. It has no runtime behavior and is never instantiated.
 *
 * `self` is typed as `SlothletSelf`, and TypeScript merges an interface of the same name into a
 * class, so a project types `self` for its whole api by extending this class from a module
 * augmentation. `slothlet typegen` emits exactly that:
 * ```ts
 * declare module "@cldmv/slothlet/runtime" {
 * 	interface SlothletSelf extends MyApi {}
 * }
 * ```
 *
 * @memberof module:@cldmv/slothlet/runtime
 * @example
 * // api.d.ts (generated by `slothlet typegen -n MyApi`) extends SlothletSelf, so in any leaf:
 * import { self } from "@cldmv/slothlet/runtime";
 * await self.math.add(1, 2); // typed from MyApi
 */
export class SlothletSelf {
}
/**
 * Live binding to the current API instance. Resolves to the running Slothlet proxy,
 * giving API modules access to all other API methods without import cycles.
 * Typed as {@link SlothletSelf}, which generated api types extend.
 *
 * @memberof module:@cldmv/slothlet/runtime
 * @type {SlothletSelf}
 * @example
 * import { self } from "@cldmv/slothlet/runtime";
 * // Inside an API function:
 * const result = await self.math.add(1, 2);
 */
export const self: SlothletSelf;
/**
 * The current ambient context object. Seeded at instance startup via `config.context` and
 * persists for the lifetime of the instance. `api.slothlet.context.run()` and `.scope()` can
 * temporarily override it for the duration of a single call, after which the previous context
 * is restored. Readable and writable.
 *
 * @memberof module:@cldmv/slothlet/runtime
 * @type {object}
 * @example
 * import { context } from "@cldmv/slothlet/runtime";
 * // Read the ambient context set via config.context or written by a previous call:
 * const userId = context.userId;
 * // context.run() overrides it only for the duration of that one call:
 * await api.slothlet.context.run({ userId: 42 }, myFn);
 */
export const context: object;
/**
 * Current Slothlet instance identifier. Unique per `slothlet()` call; useful when
 * multiple Slothlet instances coexist and you need to identify which one is active.
 *
 * @memberof module:@cldmv/slothlet/runtime
 * @type {string}
 * @example
 * import { instanceID } from "@cldmv/slothlet/runtime";
 * console.log(instanceID); // e.g. "slothlet-1"
 */
export const instanceID: string;
//# sourceMappingURL=runtime.d.mts.map