name: 🚀 Release PR Creation

on:
  push:
    branches-ignore: [master, main]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  check-and-create-release-pr:
    uses: CLDMV/.github/.github/workflows/release-workflow.yml@master
    with:
      package_name: "@cldmv/slothlet"
      node_version: "lts/*"
      test_command: "npm test"
      build_command: "npm run build:ci"
    secrets: inherit
