name: Release and Publish

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  publish-package:
    if: |
      (github.event_name == 'push' && 
       (contains(github.event.head_commit.message, 'release:') || 
        contains(github.event.head_commit.message, 'release!:'))) ||
      (github.event_name == 'pull_request' && 
       github.event.action == 'closed' && 
       github.event.pull_request.merged == true && 
       contains(github.event.pull_request.title, 'release:'))
    uses: CLDMV/.github/.github/workflows/publish-workflow.yml@master
    with:
      package_name: "@cldmv/slothlet"
      node_version: "lts/*"
      test_command: "npm test"
      build_command: "npm run build:ci"
      publish_command: "npm publish --access public"
    secrets: inherit
